apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-api
  labels:
    app: grocery-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grocery-api
  template:
    metadata:
      labels:
        app: grocery-api
      annotations:
        checksum/ssh-key: "${SSH_KEY_CHECKSUM}"
    spec:
      containers:
      - name: grocery-api
        image: grocery-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: grocery-api-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: grocery-api-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grocery-api-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: DEBUG
          value: "False"
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
