apiVersion: v1
kind: Service
metadata:
  name: grocery-api-service
spec:
  selector:
    app: grocery-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  type: NodePort
  externalTrafficPolicy: Local
