apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: celery
    spec:
      containers:
        - args:
            - celery
            - -A
            - grocery_api
            - worker
            - -l
            - INFO
          envFrom:
            - configMapRef:
                name: env
          image: grocery_api:latest
          imagePullPolicy: Never
          name: celery
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /app
              name: celery-cm0
            - mountPath: /app/src/staticfiles
              name: static-volume
            - mountPath: /app/src/mediafiles
              name: media-volume
      restartPolicy: Always
      volumes:
        - configMap:
            name: celery-cm0
          name: celery-cm0
        - name: static-volume
          hostPath:
            path: /tmp/static-volume
            type: DirectoryOrCreate
        - name: media-volume
          hostPath:
            path: /tmp/media-volume
            type: DirectoryOrCreate
