kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: grocery-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=256Mi
  extraMounts:
  - hostPath: /tmp/postgres-data
    containerPath: /tmp/postgres-data
  - hostPath: /tmp/redis-data
    containerPath: /tmp/redis-data
  - hostPath: /tmp/static-volume
    containerPath: /tmp/static-volume
  - hostPath: /tmp/media-volume
    containerPath: /tmp/media-volume
