apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-deployment.yaml
  - app-service.yaml
  - configmap.yaml
  - postgres-deployment.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - secrets.yaml

images:
  - name: gcr.io/PROJECT_ID/grocery-api
    newName: gcr.io/PROJECT_ID/grocery-api
    newTag: initial
