apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: static-volume
  name: static-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
