name: CI

on:
  pull_request:
    branches: ["dev"]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AFRICAS_TALKING_USERNAME: ${{ secrets.AFRICAS_TALKING_USERNAME }}
      AFRICAS_TALKING_API_KEY: ${{ secrets.AFRICAS_TALKING_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      DEBUG: 'False'

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8 bandit safety

    - name: Run Black
      run: |
        black . --check

    - name: Run Flake8
      run: |
        flake8 . --max-line-length=100 --exclude=migrations,venv,.venv

    - name: Create migrations
      run: |
        cd src
        python manage.py makemigrations
      env:
        DATABASE_NAME: postgres
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432

    - name: Run migrations
      run: |
        cd src
        python manage.py migrate
      env:
        DATABASE_NAME: postgres
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
        DEBUG: 'False'

    - name: Run tests with coverage
      run: |
        cd src
        pytest --cov --cov-report=xml --cov-report=term --cov-fail-under=70 --disable-warnings
      env:
        DATABASE_NAME: postgres
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
        ALLOWED_HOSTS: 'localhost,127.0.0.1'
        DEBUG: 'False'
        DJANGO_SETTINGS_MODULE: 'grocery_api.test_settings'
        PYTHONPATH: ${{ github.workspace }}/src

    - name: Upload coverage results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./src/coverage.xml
        fail_ci_if_error: true
        verbose: true

    - name: Generate coverage badge
      uses: actions/github-script@v7
      if: github.ref == 'refs/heads/main'
      with:
        script: |
          const fs = require('fs');
          const xml2js = require('xml2js');

          // Parse coverage XML
          const parser = new xml2js.Parser();
          const xml = fs.readFileSync('./src/coverage.xml', 'utf8');

          parser.parseString(xml, (err, result) => {
            if (err) {
              console.error('Error parsing coverage XML:', err);
              return;
            }

            const coverage = result.coverage.$.line-rate * 100;
            const color = coverage >= 80 ? 'brightgreen' :
                         coverage >= 70 ? 'green' :
                         coverage >= 60 ? 'yellowgreen' :
                         coverage >= 50 ? 'yellow' : 'red';

            // Create badge using shields.io
            const badgeUrl = `https://img.shields.io/badge/coverage-${coverage.toFixed(0)}%25-${color}`;

            // Add to README if not already there
            let readme = fs.readFileSync('README.md', 'utf8');
            if (!readme.includes('![Code Coverage]')) {
              const badgeLine = `[![Code Coverage](${badgeUrl})](https://github.com/${process.env.GITHUB_REPOSITORY}/actions)\n`;
              const titleEnd = readme.indexOf('\n\n');
              readme = readme.slice(0, titleEnd) + '\n' + badgeLine + readme.slice(titleEnd);
              fs.writeFileSync('README.md', readme);
            }
          });
        result-encoding: string
